default_hour: 9
default_minute: 0
editor: 'vim'
encrypt: true
highlight: true
indent_character: '|'
journals:
  default: /Users/matthewgleich/.local/share/jrnl/journal.txt
linewrap: 79
tagsymbols: '@'
template: "/Users/matthewgleich/.local/share/jrnl/template.txt"
timeformat: '%Y-%m-%d %H:%M'
version: v2.2
